### ISSUE TITLE
Can't work it out with sample code in README

### ISSUE THREAD

**Issue by ozbillwang** [localstack/localstack-python-client#23]
Start `localstack` container
```
$ curl -L https://raw.githubusercontent.com/localstack/localstack/master/docker-compose.yml -o docker-compose.yml
$ docker-compose up -d
$ docker-compose ps

     Name               Command          State                                                  Ports
----------------------------------------------------------------------------------------------------------------------------------------------------
localstack_main   docker-entrypoint.sh   Up      0.0.0.0:4566->4566/tcp, 4567/tcp, 4568/tcp, 4569/tcp, 4570/tcp, 0.0.0.0:4571->4571/tcp, 4572/tcp,
                                                 4573/tcp, 4574/tcp, 4575/tcp, 4576/tcp, 4577/tcp, 4578/tcp, 4579/tcp, 4580/tcp, 4581/tcp, 4582/tcp,
                                                 4583/tcp, 4584/tcp, 4585/tcp, 4586/tcp, 4587/tcp, 4588/tcp, 4589/tcp, 4590/tcp, 4591/tcp, 4592/tcp,
                                                 4593/tcp, 4594/tcp, 4595/tcp, 4596/tcp, 4597/tcp, 0.0.0.0:8080->8080/tcp
```

Run the test
```
# run in virtualenv
$ virtualenv env
$ source env/bin/activate

$ cat test.py

import boto3
import localstack_client.session
import pytest


@pytest.fixture(autouse=True)
def boto3_localstack_patch(monkeypatch):
    session_ls = localstack_client.session.Session()
    monkeypatch.setattr(boto3, "client", session_ls.client)
    monkeypatch.setattr(boto3, "resource", session_ls.resource)

sqs = boto3.client('sqs')
assert sqs.list_queues() is not None  # list SQS in localstack

$ python test.py
Traceback (most recent call last):
  File "a.py", line 13, in <module>
    assert sqs.list_queues() is not None  # list SQS in localstack
  File "xxxx/env/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "xxxx/env/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the ListQueues operation: The security token included in the request is expired
```

Got same error if run with `pytest`

```
$ pytest test.py
=============================================================== test session starts ================================================================
platform darwin -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: xxxx
collected 0 items / 1 error

====================================================================== ERRORS ======================================================================
______________________________________________________________ ERROR collecting a.py _______________________________________________________________
a.py:13: in <module>
    assert sqs.list_queues() is not None  # list SQS in localstack
../../../env/lib/python3.8/site-packages/botocore/client.py:357: in _api_call
    return self._make_api_call(operation_name, kwargs)
../../../env/lib/python3.8/site-packages/botocore/client.py:676: in _make_api_call
    raise error_class(parsed_response, operation_name)
E   botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the ListQueues operation: The security token included in the request is expired
============================================================= short test summary info ==============================================================
ERROR a.py - botocore.exceptions.ClientError: An error occurred (ExpiredToken) when calling the ListQueues operation: The security token included...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================= 1 error in 0.59s =================================================================
```
Seems it still goes with my local default AWS_PROFILE or local `~/.aws/credentials`, which token is expired.

But I can successfully run the first sample

```
$ cat first.py

#!/usr/bin/env python3
import localstack_client.session

session = localstack_client.session.Session()
sqs = session.client('sqs')
assert sqs.list_queues() is not None

s3 = session.client('s3')
s3.create_bucket(Bucket="test")
s3.create_bucket(Bucket="test123")
print(s3.list_buckets())

$ python first.py
{'ResponseMetadata': {'RequestId': '253C50774A750C99', 'HostId': 'MzRISOwyjmnup253C50774A750C997/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp', 'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/xml; charset=utf-8', 'access-control-allow-origin': '*', 'last-modified': 'Mon, 02 Nov 2020 05:33:37 GMT', 'x-amz-request-id': '253C50774A750C99', 'x-amz-id-2': 'MzRISOwyjmnup253C50774A750C997/JypPGXLh0OVFGcJaaO3KW/hRAqKOpIEEp', 'accept-ranges': 'bytes', 'content-language': 'en-US', 'cache-control': 'no-cache', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Mon, 02 Nov 2020 05:33:37 GMT', 'server': 'hypercorn-h11', 'transfer-encoding': 'chunked'}, 'RetryAttempts': 0}, 'Buckets': [{'Name': 'test', 'CreationDate': datetime.datetime(2020, 11, 2, 5, 2, 32, tzinfo=tzutc())}, {'Name': 'test123', 'CreationDate': datetime.datetime(2020, 11, 2, 5, 2, 59, tzinfo=tzutc())}], 'Owner': {'DisplayName': 'webfile', 'ID': 'bcaf1ffd86f41161ca5fb16fd081034f'}}
```

**Comment by whummer** [comment]
Thanks for reporting @ozbillwang . Not sure how it works exactly with `pytest`, but my assumption is that the code accessing the APIs (e.g., `sqs.list_queues`) would have to be inside a test method (not at the root scope) for the `@pytest.fixture` to actually become effective. 

Sorry I can't be of more help here, but this seems like a general Python/pytest usage issue, rather than a LocalStack issue. Please keep us posted how it goes. Thanks!
